package main

var Symbols = []string{
	"BTCUSD", "LTCUSD", "LTCBTC", "ETHUSD", "ETHBTC", "ETCBTC", "ETCUSD", "RRTUSD", "RRTBTC", "ZECUSD", "ZECBTC", "XMRUSD", "XMRBTC", "DSHUSD", "DSHBTC", "BCUBTC", "BCUUSD", "BTCEUR", "XRPUSD", "XRPBTC", "IOTUSD", "IOTBTC", "IOTETH", "EOSUSD", "EOSBTC", "EOSETH", "SANUSD", "SANBTC", "SANETH", "OMGUSD", "OMGBTC", "OMGETH", "BCHUSD", "BCHBTC", "BCHETH", "NEOUSD", "NEOBTC", "NEOETH", "ETPUSD", "ETPBTC", "ETPETH", "QTMUSD", "QTMBTC", "QTMETH", "BT1USD", "BT2USD", "BT1BTC", "BT2BTC", "AVTUSD", "AVTBTC", "AVTETH", "EDOUSD", "EDOBTC", "EDOETH", "BTGUSD", "BTGBTC", "DATUSD", "DATBTC", "DATETH",
}
